
mathematica-stdout() {/usr/local/Wolfram/Mathematica/9.0/Executables/mathematica $@;}
mathematica() {/bin/nohup /usr/local/Wolfram/Mathematica/9.0/Executables/mathematica $@ 2> /dev/null > /dev/null &;}

export TASKDDATA=/var/lib/taskd
export GITCLONES=~/git-clones

alias tasksync="python2 ~/.task/trellowarrior.py ~/.task/trellowarrior.conf"

source ~/.zpreztorc
