PHD_DIR=phd
# TensorFlow / ComputeCpp

export TF_NEED_OPENCL=1
export HOST_CXX_COMPILER=/usr/bin/clang++
export HOST_C_COMPILER=/usr/bin/clang
export COMPUTECPP_TOOLKIT_PATH=/usr/local/computecpp
export COMPUTE=:0

